install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.73.0/hugo_0.73.0_Linux-64bit.deb
  - sudo dpkg -i hugo_0.73.0_Linux-64bit.deb

script:
  - hugo -t hugo-coder # This commands builds your website on travis

deploy:
  local_dir: public
  repo: tomsanbear/tomsanbear.github.io
  target_branch: master 
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  email: thomas@santerre.xyz
  name: "tomsanbear-bot"
  on:
    branch: master
  fqdn: santerre.xyz
  keep_history: true