language: go

go:
  - "1.12" # This uses automatically the latest version of go

install:
  - go get github.com/spf13/hugo # This provides the latest version of Hugo to Travis CI

script:
  - hugo -t hugo-coder # This commands builds your website on travis

deploy:
  local_dir: public
  repo: tomsanbear/tomsanbear.github.io
  target_branch: master 
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  email: thomas@santerre.xyz
  name: "tomsanbear-bot"
  on:
    branch: master