baseurl = "https://santerre.xyz"
title = "santerre.xyz"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
googleAnalytics = "UA-84988878-1"

[params]
    author = "Thomas Santerre" 
    description = "My personal web page, still a WIP"
    keywords = "blog,developer,personal"
    info = "Full Stack Developer and Cat enthusiast"
    avatarurl = "images/avatar.jpg"
    footercontent = "Still a work in progress, come back later, or just follow my git commits."

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false
    math = true

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []
    
    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/tomsanbear/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/tomsanbear/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 5
    url = "https://medium.com/@tomsanbear"
[[params.social]]
    name = "Email"
    icon = "fas fa-envelope"
    weight = 5
    url = "mailto:thomas@santerre.xyz"

[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "/posts/"

        [[languages.en.menu.main]]
        name = "Projects"
        weight = 3
        url = "/projects/"

        [[languages.en.menu.main]]
        name = "Currently Reading"
        weight = 5
        url = "/books/"